### PR TITLE
Added tls options to dev/local runtime.

### PR DESCRIPTION
**Pull request by afinch7**
Added additional options to dev/local server for tls. Just figured I would get the ball rolling for https://github.com/superfly/fly/issues/143.

-  `--use-tls` switches everything over to a https server.
- `--tls-key-path` is for specifying a path to a key.
- `--tls-cert-path` is for specifying a path to a cert.

It should default to a dev certificate and key if none is specified.

I refactored the `Server` class to be a wrapper for a http server instead of a extension. This is likely to cause some issues, but I don't really see any other good solutions.

### CODE REVIEW

**Comment by mrkurt** [comment]
Nice! Thanks for this. When this is ready I'll make a pre-release npm. I _think_ your changes to `server.ts` are fine, but we'll need to test it against our live build to make sure it's embedded properly.

**Comment by afinch7** [comment]
You can merge this when ready. I've moved on to working on fly.rs for new features.

**Comment by Spaceghost** [comment]
Is this ready? Unrelated, is fly.rs no more? It got archived today.

**Comment by mrkurt** [comment]
@Spaceghost we've stopped working on fly.rs in favor of [Deno](https://github.com/denoland/deno).

**Pull request closed without merging**
