### PR TITLE
App example: Matomo tracking

### PR DESCRIPTION
**Pull request by OKNoah**
Unfortunately the [official Matomo node package](https://www.npmjs.com/package/matomo-tracker) doesn't work properly in the Fly environment. This is updated to be a more ES6/7+ version example. There is also a repo: https://github.com/OKNoah/matomo-nodejs-tracker. Note that `matomo.trackBulk` was removed while debugging and is currently not added back.

Matomo was previously known as Piwik. It's an open source alternative to Google Analytics/Heap/Mixpanel that you can deploy with Docker via https://hub.docker.com/_/matomo/ /

### CODE REVIEW

**Comment by mrkurt** [comment]
This is awesome. Do you feel like making it into an npm lib people can include in other projects? This seems super useful to include in other apps, and the api you built makes it seem like something I'd want to install + require from code.

**Comment by OKNoah** [comment]
@mrkurt Totally. Maybe I'll throw up a beta right now.

**Comment by OKNoah** [comment]
Testing and working on this still on my agenda, btw.

**Comment by OKNoah** [comment]
It is still coming along!

**Comment by OKNoah** [comment]
Any interest in this still?

**Pull request closed without merging**
