### PR TITLE
feat: parse all cli options and commands using a new parser script

### PR DESCRIPTION
**Pull request by pudility**
This PR allows us to parse every option we receive. 

### Benefits
 - Allows options and commands to be in any order #58
 - Every option and command is tested
 - Every option and command work
 - Customizable if we need to change anything down the road

### Usage
```
$ fly test --path foo
$ fly --path foo test # this also works
$ fly -p foo test # this also works

# more examples
$ fly --port 1234 server --uglify -i # start server on port 1234 enable both uglify and inspect
$ fly secrets set foo
$ fly secrets set --from-file foo
```
<details>
<summary>Usage</summary>
<br>

```
$ fly
Fly CLI

	 Usage:  fly [command] [options]

	 Options:

	 - app (--app, -a): App to use for commands.
	 - env (--env, -e): Environment to use for commands.
	 - token (--token, -t): Fly Access Token (can be set via environment FLY_ACCESS_TOKEN)
	 - from-file (--from-file, -f): Use a file's contents as the secret value.
	 - path (--path, -p): Test from a specific path, defaults to {test,spec}/**/*.{test,spec}.js
	 - port (--port, -p): Port to bind to
	 - uglify (--uglify, -u): uglify your code like we'll use in production (warning: slow!)
	 - inspect (--inspect, -i): use the v8 inspector on your fly app

	 Commands:

	 - version: The current version of Fly CLI
	 - apps: Manage Fly apps.
	 - create: Create a Fly app.
	 - orgs: Manage Fly orgs.
	 - deploy: Deploy your local Fly app.
	 - releases: Manage Fly apps.
	 - secrets: Manage your Fly app secrets.
	 - set: Set a secret to use in your config.
	 - test: Run unit tests, defaults to {test,spec}/**/*.{test,spec}.js
	 - server: Run the local Fly development server
	 - hostnames: Manage Fly app's hostnames.
	 - add: Add a hostname to your fly app.
	 - login: Login to Fly and save credentials locally.
	 - fetch: Fetch your Fly app locally.
	 - logs: Logs from your app.
```

</details>

### COMMAND/OPTION object structure
[snippet](https://github.com/pudility/fly/blob/flags/src/cmd/parser.ts#L22-L37)
```JavaScript
  /*
  * add takes an array of options. Options are objects in this format:
  * @property name [required] this is the name that can the user can type to get
                           this option or command. for commands the user can use
                           the name and for options the user can use either
                           --the-name or -the first letter of the name eg. name:
                           from-file will be triggered by: -f || --from-file
  * @property type [required] the type of option. this can be either COMMAND or OPTION
  * @property action [required (for commands)] the function to be run when a
                                            command is given by the user.
  * @property mapTo [optional] the name of the object returned from getOptions
  * @property description [optional] description of the command or option
  * @property usage [optional] the useage of a particular command or option
  * @property takesArguments [optional] allows commands to take arguments
  * @property bool [optional] makes the option not take any value
  */
```
### Testing
[Every command and option is tested to make sure that they work properly.](https://github.com/pudility/fly/blob/flags/test/command.spec.ts)

### CODE REVIEW

**Comment by jeromegn** [comment]
Very nice!

Is there a way to restrict the options that show up in the help text? Some options are global and some are specific to a subcommand. Doesn't make a whole lot of sense to show them all in the main usage, makes it harder to use.

**Comment by pudility** [comment]
For sure. I will get right on that.

**Comment by pudility** [comment]
@jeromegn Added an option to not show in help - I applied it to a few of the commands, feel free to suggest more if you see any I missed.

**Comment by jeromegn** [comment]
@pudility oh I had not even noticed those, but yes that's desirable.

Had you noticed the help for each subcommand? Does that still work?

When I say "Options", I meant the `--`-prefixed options. For example `--from-file` is only useful in the secrets subcommand and could be confusing to show in the general usage text. Same with `--uglify` and a few others.

There are only 3 global options: `--app`, `--env` and `--token`. These should be available from any command, in whatever order, even between subcommands (I think, but we could do without that.)

The rest are specific to a sub-command.

Currently, each sub-command has its own `--help` which showed the options and args it would allow.

In terms of formatting, I think it's pretty common to use a format like:

```
-a, --app <name>  This is the description of this option.
```

Essentially: `-short-name` followed by `--long-name` followed by args (if any) for that option and followed by a description.

Formatting is not as crucial as the other issues I mentioned :)

A sub-command may have multiple sub-commands of its own.

Anyway, commandpost did most of that by default for us.

**Comment by pudility** [comment]
Okay, I can do that. As for the options, can they all always be allowed but only get used for specific subcommands? For example, this would _work_:
```
$ fly server --port 3030 --from-file foo
```
But server would only recognize `--port`? Otherwise, I can try to make it so that only sub commands work with their options.

**Comment by jeromegn** [comment]
This gets closer with every commit :)

Any thoughts on subcommands of subcommands? They're not discoverable anymore:

```
$ ./lib/cmd/index.js apps --help
Fly CLI

	 Usage:  fly [command] [options]

	 Commands:

	 - version: The current version of Fly CLI
	 - apps: Manage Fly apps.
	 - orgs: Manage Fly orgs.
	 - deploy: Deploy your local Fly app.
	 - releases: Manage Fly apps.
	 - secrets: Manage your Fly app secrets.
	 - test: Run unit tests, defaults to {test,spec}/**/*.{test,spec}.js
	 - server: Run the local Fly development server
	 - hostnames: Manage Fly app's hostnames.
	 - login: Login to Fly and save credentials locally.
	 - fetch: Fetch your Fly app locally.
	 - logs: Logs from your app.

	 Options:

	 - app (--app, -a) <id>: App to use for commands.
	 - env (--env, -e) <env>: Environment to use for commands.
	 - token (--token, -t) <token>: Fly Access Token (can be set via environment FLY_ACCESS_TOKEN)
```

I would expect it to list only the commands available under `fly apps` like `fly apps create`

**Comment by pudility** [comment]
I see - yes, as soon as I finish writing tests for the above commit I will work on that.

**Comment by pudility** [comment]
I am not sure I completely understand what you are saying. Are you saying I should re-do this using the command post library, or just that I should implement the Command options for all of the sub commands/options?

**Comment by mrkurt** [comment]
Oh! I'm sorry. I didn't realize this replaced commandpost entirely. We should definitely keep using command post unless there's a really good reason to drop it in favor of custom code.

**Comment by pudility** [comment]
Okay, because this PR replaces command post - maybe we should just close it. I think that custom code is a better, but obviously I am biased 😄. I think there are a lot of small issues with command post. One of which being that commands must be in a specific order, another being that some commands just don't work - for example:
```bash
$ fly hostnames add abc --token abc
CommandpostError: unknown option --token
Add a hostname to your fly app.

  Usage: fly hostnames add [--] <hostname>


    at Command._parseRawArgs ...
$ fly hostnames add abc
Error: --token option or environment variable FLY_ACCESS_TOKEN needs to be set.
    ...
```
Another reason to use custom code is because we can test every scenario to make sure things like the issue above do not happen.

Anyway, Let me know what you think, and I will do whatever you think is best - that is just my reasoning.

**Comment by jeromegn** [comment]
> One of which being that commands must be in a specific order, another being that some commands just don't work

I think extending the command options like @mrkurt mentioned would solve that issue. if every subcommand options also accept the root options, then you can use `--app` and `--token` anywhere.

> Another reason to use custom code is because we can test every scenario to make sure things like the issue above do not happen.

You can definitely test commandpost CLI commands. There are decent examples in the commandpost repo: https://github.com/vvakame/commandpost/blob/master/test/commandSpec.ts

We prefer using commandpost because it's already there and there's a smaller change in our code we can make to make it work like we want it to.

Writing our own custom CLI parser is too much like reinventing the wheel. There are a lot of other parsers out there that would also work.

The main criteria for choosing the CLI package was that it allowed sub commands in a nice manner. We used to use commander.js, but it required us to create different files for all sub commands (à la git.)

commandpost also is all TypeScript and gives us "some" type safety with arguments and options. It's not perfect but it's pretty good.

We can also improve commandpost by fixing the issues we encounter upstream, in their repo.

I think the smallest change here is to extend all subcommand options to include the global (root) options. One challenge with this approach is getting the app name from anywhere. Right now we just check the root command if it has the app option set, but we'd need to check all subcommands if we extend the options to accept `--app`.

I'm sorry I didn't pick up on the fact that this was a big rewrite, I was under the impression you we're still using commandpost. My bad.

**Comment by pudility** [comment]
@jeromegn Its fine, that makes sense. I think it would probably be best to close this PR and make a new one. I can get started on that.

**Pull request closed without merging**
