### PR TITLE
Add js-beautify config to standarize JS formatting

### PR DESCRIPTION
**Pull request by mbyczkowski**
I have grabbed this config from another project, hopefully it's mostly sensible 🙂

### CODE REVIEW

**Comment by jeromegn** [comment]
jsbeautify had not quite cut it for me last time we played with it.

What do you think about https://standardjs.com/ ?

**Comment by mbyczkowski** [comment]
sure, standardjs looks good to me. I'm gonna look if I can set it up 👍

**Comment by mbyczkowski** [comment]
hmm, it doesn't fix as many things as I'd like, and so far auto-formatting is not working for me 😒

**Comment by mbyczkowski** [comment]
`v8env` relinting caused test failures (not sure where), but it was a huge change, so best to just drop it one-by-one

**Comment by jeromegn** [comment]
Given we're going to be converting more and more JS to TypeScript, should we bother with this?

**Comment by mbyczkowski** [comment]
I agree, let's work on porting to TS quicker!

**Pull request closed without merging**
